// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDG9bq6X9H7dHtNoxwElSx2RRqYpgcbV3A',
    appId: '1:838707577560:web:0f485b8dc3130058088dad',
    messagingSenderId: '838707577560',
    projectId: 'chatspp-9e51e',
    authDomain: 'chatspp-9e51e.firebaseapp.com',
    storageBucket: 'chatspp-9e51e.firebasestorage.app',
    measurementId: 'G-8L83R814LH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgajMje8qVX7vwyiCOUz-xX5NOXNcG3TE',
    appId: '1:838707577560:android:f39a25b066937873088dad',
    messagingSenderId: '838707577560',
    projectId: 'chatspp-9e51e',
    storageBucket: 'chatspp-9e51e.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDG9bq6X9H7dHtNoxwElSx2RRqYpgcbV3A',
    appId: '1:838707577560:web:3835d287fb4c3f6b088dad',
    messagingSenderId: '838707577560',
    projectId: 'chatspp-9e51e',
    authDomain: 'chatspp-9e51e.firebaseapp.com',
    storageBucket: 'chatspp-9e51e.firebasestorage.app',
    measurementId: 'G-LR3HXWT1JZ',
  );
}
